---
title: "Cobs Genome repeat landscapes: TEislands"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    collapsed: true
    number_sections: true
    df_print: paged
  pdf_document: default
---
<STYLE TYPE="text/css">
<!--
  td{
    font-family: Arial; 
    font-size: 8pt;
    padding:0px;
    cellpadding="0";
    cellspacing="0"
  }
  th {
    font-family: Arial; 
    font-size: 8pt;
    height: 20px;
    font-weight: bold;
    text-align: right;
    background-color: #ccccff;
  }
  table { 
    border-spacing: 0px;
    border-collapse: collapse;
  }
--->
</STYLE>

```{r}
source("~/sciebo/librarySchrader.R")
library(ggplot2)
library(viridisLite)
library(dplyr)
color = grDevices::colors()[grep('gr(a|e)y', grDevices::colors(), invert = T)]
```

```{r}
type<-"TE islands"
dataTEi<-read.csv("/Users/lukas/sciebo/Projects/CardiocondylaGenome/CardioMinION/annotation/Cobs.alpha.v.2.1.repeats/landscapes/TEislands/Cobs.fa.TEisl.align.landscape.My.Rname.tab",sep="\t",skip=1,check.names=FALSE)
colnames(dataTEi)[4:ncol(dataTEi)]<-round(as.numeric(gsub("\\[(.*?)\\;(.*?)\\[","\\2",colnames(dataTEi)[4:ncol(dataTEi)],perl=T)),1)
dataMelt<-reshape2::melt(dataTEi, id.vars=colnames(dataTEi)[1:3])

dataTEiclass<-read.csv("/Users/lukas/sciebo/Projects/CardiocondylaGenome/CardioMinION/annotation/Cobs.alpha.v.2.1.repeats/landscapes/TEislands/Cobs.fa.TEisl.align.landscape.My.Rclass.tab",sep="\t",skip=1,check.names=FALSE)
colnames(dataTEiclass)[4:ncol(dataTEiclass)]<-round(as.numeric(gsub("\\[(.*?)\\;(.*?)\\[","\\2",colnames(dataTEiclass)[4:ncol(dataTEiclass)],perl=T)),1)
dataMeltclass<-reshape2::melt(dataTEiclass, id.vars=colnames(dataTEiclass)[1:1])

dataTEifam<-read.csv("/Users/lukas/sciebo/Projects/CardiocondylaGenome/CardioMinION/annotation/Cobs.alpha.v.2.1.repeats/landscapes/TEislands/Cobs.fa.TEisl.align.landscape.My.Rfam.tab",sep="\t",skip=1,check.names=FALSE)
colnames(dataTEifam)[4:ncol(dataTEifam)]<-round(as.numeric(gsub("\\[(.*?)\\;(.*?)\\[","\\2",colnames(dataTEifam)[4:ncol(dataTEifam)],perl=T)),1)
dataMeltfam<-reshape2::melt(dataTEifam, id.vars=colnames(dataTEifam)[1:2])

```

```{r}
#24664824 = TEisland coverage
#24664824 = total genome size
#24664824-24664824=168386404
ggplot(dataMeltclass, aes(fill=Rclass, x=as.numeric(as.character(variable)),y=100*value/24664824)) + ylab("% TEisland")+ xlab("MYA")+
    geom_bar(position="stack", stat="identity")+theme_classic()+theme(legend.position = "bottom",axis.text.x = element_text(angle = -45))+ggtitle(type)

dev.print(pdf, "/Users/lukas/sciebo/Projects/CardiocondylaGenome/CardioMinION/annotation/Cobs.alpha.v.2.1.repeats/landscapes/TEislands/Cobs.fa.TEislands.broad.pdf")
```

LTR only
```{R}

set.seed(10)
LTRs<-subset(dataMeltfam,Rclass=="LTR" & Rfam!="Gypsy-Cigr"&Rfam!="LTR"&Rfam!="DIRS"&Rfam!="Pao")
LTRs<-subset(dataMeltfam,Rclass=="LTR")

LTRs$Rfam<-as.factor(as.character(LTRs$Rfam))
colSel<-sample(color, length(levels(LTRs$Rfam)))

cols <- colorRampPalette(brewer.pal(8,"Blues"))(9)
g1<-ggplot(LTRs, aes(fill=Rfam, x=as.numeric(as.character(variable)),y=100*value/24664824)) + ylab("% genome")+ xlab("MYA")+
    geom_bar(position="stack", stat="identity")+theme_classic()+theme(legend.position = "bottom",axis.text.x = element_text(angle = -45))+ggtitle(type)
g1
dev.print(pdf,"/Users/lukas/sciebo/Projects/CardiocondylaGenome/CardioMinION/annotation/Cobs.alpha.v.2.1.repeats/landscapes/TEislands/Cobs.TEisl.LTR.0-50.pdf")
g2<-ggplot(LTRs, aes(fill=Rfam, x=as.numeric(as.character(variable)),y=100*value/24664824)) + ylab("% genome")+ xlab("MYA")+
    geom_bar(position="stack", stat="identity")+theme_classic()+theme(legend.position = "bottom",axis.text.x = element_text(angle = -45))+xlim(0,10)+ggtitle(type)
g2
dev.print(pdf,"/Users/lukas/sciebo/Projects/CardiocondylaGenome/CardioMinION/annotation/Cobs.alpha.v.2.1.repeats/landscapes/TEislands/Cobs.TEisl.LTR.0-10.pdf")


#+scale_fill_manual(values = c("BEL"=cols[1],
#                                                                                             "Copia"=cols[3],
#                                                                                             "Gypsy"=goodCols[3],
#                                                                                             "LARD"=cols[6],
#                                                                                             "TRIM"=cols[9]
#                                                                                             ))

```
Gypsy only
```{R}
set.seed(20)
Gypsy<-subset(dataMelt,Rfam=="Gypsy" )
tmp<-Gypsy %>%
    group_by(Rname) %>%
    summarise(score=max(value))
Gypsy2<-subset(Gypsy,Rname %in% tmp$Rname[tmp$score>500])
Gypsy2$Rname<-as.factor(as.character(Gypsy2$Rname))
colSel<-sample(color, length(levels(Gypsy2$Rname)))
ggplot(Gypsy2, aes(fill=Rname, x=as.numeric(as.character(variable)),y=100*value/24664824)) + ylab("% genome")+ xlab("MYA")+
    geom_bar(position="stack", stat="identity")+theme_classic()+theme(legend.position = "none")+theme(legend.position = "none",axis.text.x = element_text(angle = -45))+ggtitle(type)
dev.print(pdf,"/Users/lukas/sciebo/Projects/CardiocondylaGenome/CardioMinION/annotation/Cobs.alpha.v.2.1.repeats/landscapes/TEislands/Cobs.TEisl.Gypsy.pdf")


Gypsy3<-subset(Gypsy,Rname %in% tmp$Rname[tmp$score>10000])
Gypsy3$Rname<-as.factor(as.character(Gypsy3$Rname))
colSel<-sample(color, length(levels(Gypsy3$Rname)))
ggplot(Gypsy3, aes(fill=Rname, x=as.numeric(as.character(variable)),y=100*value/24664824)) + ylab("% genome")+ xlab("MYA")+
    geom_bar(position="stack", stat="identity")+theme_classic()+theme(legend.position = "bottom",legend.key.size = unit(1,"mm"),axis.text.x = element_text(angle = -45))+ggtitle(type)+xlim(0,20)

dev.print(pdf,"/Users/lukas/sciebo/Projects/CardiocondylaGenome/CardioMinION/annotation/Cobs.alpha.v.2.1.repeats/landscapes/TEislands/Cobs.TEisl.Gypsy.mostAbundant.pdf")

```


